template_path: templates/agora.yaml
stack_name: agora
dependencies:
  - essentials
  - sandcastlevpc
parameters:
  # Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  KeyName: agora
  # Select a VPC that allows instances access to the Internet.
  VpcId: vpc-0e9b80dc470a797d5  # us-east-1-sandcastlevpc-VPCId
  # Select at least two subnets in your selected VPC, one subnet per Availability Zone
  SubnetId:
    - subnet-02f2acd15e5be53cd  # us-east-1-sandcastlevpc-PublicSubnet
    - subnet-031359c53fce9b312  # us-east-1-sandcastlevpc-PublicSubnet1
  InstanceType: t2.micro
