template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpn-sandcastlevpc
dependencies:
  - sandcastlevpc
parameters:
  PeeringConnectionId: pcx-66912d0e
  VpcPrivateRouteTable: rtb-03749e8c822352561
  VpcPublicRouteTable: rtb-0707730d3016e2737
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-route-config.yaml --create-dirs -o remote-templates/peer-route-config.yaml"
