template_path: "remote/sc-enduser-iam.yaml"
stack_name: "sc-enduser-iam"
dependencies:
  - "prod/essentials.yaml"
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/scipoolprod-sc-lib-infra/master/iam/sc-enduser-iam.yaml --create-dirs -o templates/remote/sc-enduser-iam.yaml"
